[package]
name = "amethyst-imgui"
version = "0.1.0"
description = "imgui library for amethyst"
license = "CC0-1.0"
authors = ["Awpteamoose <cargo@awpteamoose.my.to>"]
repository = "https://github.com/Awpteamoose/amethyst-imgui"
readme = "README.md"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
gfx = "0.17"
glsl-layout = { version = "0.1.1", features = ["gfx"] }
shred-derive = "0.6"
shred = "0.8"

imgui = { path = "./imgui-rs" }
imgui-gfx-renderer = { path = "./imgui-rs/imgui-gfx-renderer" }
imgui-winit-support = { path = "./imgui-rs/imgui-winit-support" }

[[example]]
name = "demo_window"
path = "examples/demo_window.rs"
