[package]
name = "amethyst-imgui"
version = "0.1.0"
description = "imgui library for amethyst"
license = "CC0-1.0"
authors = ["Awpteamoose <cargo@awpteamoose.my.to>"]
repository = "https://github.com/Awpteamoose/amethyst-imgui"
readme = "README.md"

[dependencies]
amethyst = "0.10"
gfx = "0.17"
glsl-layout = "0.1"
shred-derive = "0.5"
shred = "0.7"

glium = { version = "0.22", default-features = true }
imgui = "0.0.21"
imgui-gfx-renderer = "0.0.21"
