[package]
name = "amethyst-imgui"
version = "0.1.0"

[dependencies]
amethyst = "0.8.0"
gfx = "0.17.1"
glsl-layout = "0.1.1"
shred-derive = "0.5.0"
shred = "0.7.0"

glium = { version = "0.22", default-features = true }
imgui = { git = "https://github.com/Gekkio/imgui-rs" }
imgui-gfx-renderer = { git = "https://github.com/Gekkio/imgui-rs" }
